### ISSUE TITLE
changing background color / link colors (this could be user error!!)

### ISSUE THREAD

**Issue by LucyMcGowan** [malcolmbarrett/kakashi-quarto-theme#3]
I am trying to change the background of the title side and the link color. I have added 

```
$link-color: #70001A;
```

and

```
#title-slide {
  background-size: cover;
  background-color: #fff;
  color: #404040;
}
```

to my custom CSS but the former seems to be defaulting to the theme regardless of what I put in and the latter does this weird thing:
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/8431897/213778455-d670bce3-3b0c-4b33-a8ae-fc140f0b84d2.png">

**Comment by malcolmbarrett** [comment]
I'm not sure what's up with the first one, but the second one is because quarto does title styling weirdly: https://github.com/malcolmbarrett/kakashi-quarto-theme/blob/c147c0f2b2fe3e2d7efeca21de0843f693fec421/_extensions/kakashi/_extension.yml#L23-L25

**Comment by malcolmbarrett** [comment]
How are you including your css file?

**Comment by LucyMcGowan** [comment]
Ohhh so do I need to update the yaml for the title? This is how I include
my css:

format:
  kakashi-revealjs:
    theme: [custom.scss]
    slide-number: true
    chalkboard: true
*Lucy D'Agostino McGowan, PhD*
Assistant Professor
Department of Statistical Sciences
Wake Forest University
✉️ ***@***.***
🌐 lucymcgowan.com <https://www.lucymcgowan.com>

**Comment by malcolmbarrett** [comment]
> Ohhh so do I need to update the yaml for the title?

I think so

I wonder if you need something like `theme: [kakashi.scss, custom.scss]`?

**Comment by LucyMcGowan** [comment]
Do you mean I would have the first link to the path within the extension
(like [_extensions/malcombarret/kakashi/kakshi.scss, custom.scss]? as
written it says the first doesn't exist.

**Comment by malcolmbarrett** [comment]
Hm I don't know. I thought it might resolve it itself

**Comment by malcolmbarrett** [comment]
Does this work? I don't know why it would, just thinking through what's different about the link color

`$pink: #70001A;`

**Comment by LucyMcGowan** [comment]
:( did not work. I think the key is anything that is input as a quarto variable in the .scss doc seems to not be able to be "overwritten" by my custom .scss file? (so less a problem with $pink and more with $link-color)

**Comment by malcolmbarrett** [comment]
I wonder if it's because I'm not using `!default` in the sass file https://sass-lang.com/documentation/variables#default-values

Will you try adding that in your local copy of the kakashi.scss file, like `$link-color: $pink !default;`?

**Comment by LucyMcGowan** [comment]
That's it!

**Comment by malcolmbarrett** [comment]
nice, I'll make that change to the repo copy

**Comment by malcolmbarrett** [comment]
Fixed on main. Also fixed a few other things so you might want to copy it over
