### ISSUE TITLE
Not incremented list possible?

### ISSUE THREAD

**Issue by LucyMcGowan** [malcolmbarrett/kakashi-quarto-theme#4]
Is it possible to *not* increment a list? For our workshop we often have an application exercise where we list 3 or 4 steps and I want to be able to have them all there without any greyed out

**Comment by malcolmbarrett** [comment]
https://quarto.org/docs/presentations/index.html#incremental-lists

Use `{.nonincremental}` I think, but I haven't tried it yet

**Comment by LucyMcGowan** [comment]
I didn't work :( is there something hardcoded that makes all lists incremental?

**Comment by malcolmbarrett** [comment]
```
::: {.nonincremental}
- thing 1
- thing 2
- thing 3
:::
```

that works for me 🤔

**Comment by malcolmbarrett** [comment]
but yes, it's set as the default for this theme: https://github.com/malcolmbarrett/kakashi-quarto-theme/blob/c147c0f2b2fe3e2d7efeca21de0843f693fec421/_extensions/kakashi/_extension.yml#L29

**Comment by LucyMcGowan** [comment]
OH user error on my part (sorry!!), I was trying to set the global
{.nonincremental} on the slide like

## Exercise {.nonincremental}

1. ..
2. ..
3...
*Lucy D'Agostino McGowan, PhD*
Assistant Professor
Department of Statistical Sciences
Wake Forest University
✉️ ***@***.***
🌐 lucymcgowan.com <https://www.lucymcgowan.com>
